/* Drop all views */

DROP VIEW IF EXISTS BSLVC_ALL;
DROP VIEW IF EXISTS BSLVC_LEXICAL;
DROP VIEW IF EXISTS BSLVC_GRAMMAR;
DROP VIEW IF EXISTS BSLVC_SPOKEN;
DROP VIEW IF EXISTS BSLVC_WRITTEN;
DROP VIEW IF EXISTS BSLVC_ALL_IMPUTED;
DROP VIEW IF EXISTS BSLVC_LEXICAL_IMPUTED;
DROP VIEW IF EXISTS BSLVC_GRAMMAR_IMPUTED;
DROP VIEW IF EXISTS BSLVC_SPOKEN_IMPUTED;
DROP VIEW IF EXISTS BSLVC_WRITTEN_IMPUTED;
DROP VIEW IF EXISTS Informants_View;

/* Drop all data tables */

DROP TABLE IF EXISTS Informants;
DROP TABLE IF EXISTS LexicalItems;
DROP TABLE IF EXISTS LexicalItemsImputed ;
DROP TABLE IF EXISTS SpokenItems ;
DROP TABLE IF EXISTS SpokenItemsImputed ;
DROP TABLE IF EXISTS WrittenItems ;
DROP TABLE IF EXISTS WrittenItemsImputed ;

